default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: survey_snake_development

test:
  <<: *default
  database: survey_snake_test

production:
  <<: *default
  database: survey_snake_production
  username: survey_snake
  password: <%= ENV['SURVEY_SNAKE_DATABASE_PASSWORD'] %>
